2024-07-11 00:15:52,372 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [123]
2024-07-11 00:20:51,132 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [123]
2024-07-11 00:23:30,902 INFO EDITED RECORD | database: fil_bot | table: fil | id | 123 | partner_id | 546
2024-07-11 12:18:33,301 INFO EDITED RECORD | database: fil_bot | table: fil | id | 123 | ['partner_id', 'kisses'] | [789, 123]
2024-07-11 12:23:19,748 ERROR REQUEST ERROR
2024-07-11 12:23:42,957 ERROR REQUEST ERROR
2024-07-11 12:27:05,244 ERROR REQUEST ERROR
2024-07-11 12:43:24,462 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [392601874]
2024-07-11 12:44:26,562 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [392601874]
2024-07-11 12:48:39,014 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [1830835384]
2024-07-11 12:49:54,269 INFO ADDED NEW RECORD | database: fil_bot | table: fil | ['id'] | [1830835384]
2024-07-11 12:49:54,616 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['partner_id', 'relation_date'] | ['392601874', '11.7.2024']
2024-07-11 12:49:54,620 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['partner_id', 'relation_date'] | [1830835384, '11.7.2024']
2024-07-11 13:08:42,280 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-07-11 13:08:58,687 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['partner_id', 'relation_date'] | ['0', '0']
2024-07-11 13:08:58,692 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['partner_id', 'relation_date'] | ['0', '0']
2024-07-11 13:21:44,745 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['partner_id', 'relation_date'] | ['392601874', '11.7.2024']
2024-07-11 13:21:44,754 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['partner_id', 'relation_date'] | [1830835384, '11.7.2024']
2024-07-11 13:22:05,167 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['kisses'] | [1]
2024-07-11 13:22:05,170 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['kisses'] | [1]
2024-07-11 13:23:12,347 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['hugs'] | [1]
2024-07-11 13:23:12,349 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['hugs'] | [1]
2024-07-11 23:11:18,110 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:18,115 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:21,430 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:21,430 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 646, in __retrieve_updates
    self.__skip_updates()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 634, in __skip_updates
    self.get_updates(offset=-1)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:21,747 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:21,747 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:25,295 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:25,295 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 646, in __retrieve_updates
    self.__skip_updates()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 634, in __skip_updates
    self.get_updates(offset=-1)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:25,864 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:25,865 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:29,926 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:29,927 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 646, in __retrieve_updates
    self.__skip_updates()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 634, in __skip_updates
    self.get_updates(offset=-1)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:30,987 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:30,987 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:36,047 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:36,047 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 646, in __retrieve_updates
    self.__skip_updates()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 634, in __skip_updates
    self.get_updates(offset=-1)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:38,106 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:38,107 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:11:42,170 ERROR Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-07-11 23:11:42,170 ERROR Exception traceback:
Traceback (most recent call last):
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 646, in __retrieve_updates
    self.__skip_updates()
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 634, in __skip_updates
    self.get_updates(offset=-1)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\AlADo\PycharmProjects\fall_in_love\venv\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-07-11 23:16:51,298 INFO EDITED RECORD | database: fil_bot | table: fil | id | 392601874 | ['relation_date'] | ['24.7.2015']
2024-07-11 23:16:51,306 INFO EDITED RECORD | database: fil_bot | table: fil | id | 1830835384 | ['relation_date'] | ['24.7.2015']
